### ISSUE TITLE
[Feature] Implement TravelAgent for multi-tool travel planning

### ISSUE THREAD

**Issue by itsthemoon** [agiresearch/OpenAGI#46]
**Description:**
The goal is to create a new TravelAgent that assists users with travel planning tasks by calling and integrating the results from multiple search tools. This will expand the capabilities of AIOS to handle complex travel-related queries. Inspirations for the design of this agent are: MathAgent, RecAgent, and NarrativeAgent.

**Key Features:**
- TravelAgent will support travel-related queries by calling relevant tools such as:
  - Hotel search 
       - We will use the existing search_hotel.py tool or tripadvisor tool; need more investigation into which to use
  - Flight search
       - We will use the existing tripadvisor flights tool
  - Restaurant recommendation
       - We will use the existing tripadvisor restaurant tool 
  - General Information
       - CurrencyConverter tool (if needed)
       - Wikipedia for information about the location we are traveling to
- The TravelAgent will interpret the user's travel intent, call the appropriate sequence of tools, integrate the results, and present the user with comprehensive travel plan options

**Implementation Plan**
- [x]  Create the TravelAgent config 
- [x] Add the TravelAgent to the native_agents folder with features impemented
- [x] Add the TravelAgent to the existing agent table in `agent_factory.py` 
- [x] Complete implementation by incorporating the agent into AIOS 

**Current Limitations/Future Work**
In this current implementation plan, there are a couple of things that are not included, but would be a great additions. 
  1. Include recommended attractions in the travel plan
  2. Include the weather forecast for the proposed date of travel
